import { SvgSizes, Icons } from "./svg.types";


const DEFAULT_SIZE = {
  default: { width: '20px', height: '20px' },
  small: { width: '16px', height: '16px' },
  large: { width: '24px', height: '24px' },
};

export const ICON_SIZES: SvgSizes = {
  [Icons.Analytics]: DEFAULT_SIZE,
  [Icons.ArrowLeft]: DEFAULT_SIZE,
  [Icons.Article]: DEFAULT_SIZE,
  [Icons.Barcode]: DEFAULT_SIZE,
  [Icons.Box]: DEFAULT_SIZE,
  [Icons.Briefcase]: DEFAULT_SIZE,
  [Icons.Delete]: DEFAULT_SIZE,
  [Icons.Directories]: DEFAULT_SIZE,
  [Icons.Drafts]: DEFAULT_SIZE,
  [Icons.DraftSave]: DEFAULT_SIZE,
  [Icons.Enter]: DEFAULT_SIZE,
  [Icons.Export]: DEFAULT_SIZE,
  [Icons.Execute]: DEFAULT_SIZE,
  [Icons.Eye]: DEFAULT_SIZE,
  [Icons.ArrowSwap]: DEFAULT_SIZE,
  [Icons.Folders]: DEFAULT_SIZE,
  [Icons.History]: DEFAULT_SIZE,
  [Icons.Import]: DEFAULT_SIZE,
  [Icons.List]: DEFAULT_SIZE,
  [Icons.Manufacture]: DEFAULT_SIZE,
  [Icons.MenuMax]: DEFAULT_SIZE,
  [Icons.MenuMini]: DEFAULT_SIZE,
  [Icons.Moon]: DEFAULT_SIZE,
  [Icons.MoreVertical]: DEFAULT_SIZE,
  [Icons.Device]: DEFAULT_SIZE,
  [Icons.Logout]: DEFAULT_SIZE,
  [Icons.UserSetting]: DEFAULT_SIZE,
  [Icons.Packet]: DEFAULT_SIZE,
  [Icons.Remains]: DEFAULT_SIZE,
  [Icons.Save]: DEFAULT_SIZE,
  [Icons.Settings]: DEFAULT_SIZE,
  [Icons.Store]: DEFAULT_SIZE,
  [Icons.Synchronize]: DEFAULT_SIZE,
  [Icons.TrolleyFilled]: DEFAULT_SIZE,
  [Icons.Unit]: DEFAULT_SIZE,
  [Icons.Wallet]: DEFAULT_SIZE,
  [Icons.ChevronLeft]: DEFAULT_SIZE,
  [Icons.ChevronRight]: DEFAULT_SIZE,
  [Icons.ChevronDown]: DEFAULT_SIZE,
  [Icons.DChevronLeft]: DEFAULT_SIZE,
  [Icons.DChevronRight]: DEFAULT_SIZE,
  [Icons.Edit]: DEFAULT_SIZE,
  [Icons.Filter]: DEFAULT_SIZE,
  [Icons.More]: DEFAULT_SIZE,
  [Icons.Print]: DEFAULT_SIZE,
  [Icons.Reload]: DEFAULT_SIZE,
  [Icons.Search]: DEFAULT_SIZE,
  [Icons.CheckboxEmpty]: DEFAULT_SIZE,
  [Icons.CheckboxFilled]: DEFAULT_SIZE,
  [Icons.CheckboxIndeterminate]: DEFAULT_SIZE,
  [Icons.Info]: DEFAULT_SIZE,
  [Icons.InfoNotification]: DEFAULT_SIZE,
  [Icons.Success]: DEFAULT_SIZE,
  [Icons.Error]: DEFAULT_SIZE,
  [Icons.Warning]: DEFAULT_SIZE,
  [Icons.Cross]: DEFAULT_SIZE,
  [Icons.RadioChecked]: DEFAULT_SIZE,
  [Icons.RadioEmpty]: DEFAULT_SIZE,
  [Icons.Notifications]: DEFAULT_SIZE,
  [Icons.Calendar]: DEFAULT_SIZE,
  [Icons.ArrowRight]: DEFAULT_SIZE,
  [Icons.Plus]: DEFAULT_SIZE,
  [Icons.ArrowUp]: DEFAULT_SIZE,
  [Icons.FolderShape]: DEFAULT_SIZE,
  [Icons.Document]: DEFAULT_SIZE,
  [Icons.Burger]: DEFAULT_SIZE,
  [Icons.Checkmark]: DEFAULT_SIZE,
  [Icons.Download]: DEFAULT_SIZE,
  [Icons.MainProfit]: {
    default: { width: '817px', height: '817px' },
  },
  [Icons.LicenseSuccess]: {
    default: { width: '10px', height: '10px' },
    large: { width: '12px', height: '12px' },
  },
  [Icons.LicenseExpired]: {
    default: { width: '10px', height: '10px' },
    large: { width: '12px', height: '12px' },
  },
  [Icons.LicenseNone]: {
    default: { width: '10px', height: '10px' },
    large: { width: '12px', height: '12px' },
  },
  [Icons.LicenseWarning]: {
    default: { width: '10px', height: '10px' },
    large: { width: '12px', height: '12px' },
  },
  [Icons.Clock]: {
    default: { width: '12px', height: '12px' },
    large: { width: '16px', height: '16px' },
  },
  [Icons.ArrowMiniDown]: {
    default: { width: '12px', height: '12px' },
    large: { width: '16px', height: '16px' },
  },
  [Icons.ArrowMiniUp]: {
    default: { width: '12px', height: '12px' },
    large: { width: '16px', height: '16px' },
  },
  [Icons.Spinner]: {
    default: { width: '36px', height: '36px' },
    small: { width: '28px', height: '28px' },
    large: { width: '56px', height: '56px' },
  },
  [Icons.Avatar]: {
    default: { width: '20px', height: '20px' },
    large: { width: '32px', height: '32px' },
  },
  [Icons.LogoFull]: {
    small: { width: 'auto', height: '20px' },
    default: { width: '79px', height: '24px' },
    large: { width: 'auto', height: '36px' },
  },
  [Icons.LogoMini]: {
    small: { width: '20px', height: '20px' },
    default: { width: '24px', height: '24px' },
    large: { width: '36px', height: '36px' },
  },
  [Icons.LogoText]: {
    small: { width: 'auto', height: '20px' },
    default: { width: '47px', height: '24px' },
    large: { width: 'auto', height: '36px' },
  },
};
