export enum PermissionEnum {
  None = 0,
  AllUsersEdit=1,
  AllCompaniesEdit=2,
  AllCompaniesView=3,
  AllUsersView=4,
  PermissionsEdit=5,
  PersonalAccountCreate=6,
  PersonalAccountWithLevelCreate=7,
  AllPersonalAccountsView=8,
  OwnPersonalAccountView=9,
  AnyLicenseCreate=10,
  AnyLicenseRevoke=11,
  AnyLicenseCancel=12,
  AllLicensesView=13,
  OwnLicensesView=14,
  LicenseActivate=15,
  OwnLicensesRevoke=16,
  AnyPersonalAccountDeposit=17,
  AnyPersonalAccountWithdrawal=18,
  AllBalanceHistoriesView=19,
  OwnBalanceHistoryView=21,
  AnyPersonalAccountOverdraftEdit=20,
  Process_1C=23,
  CreateTimetableSpansManually = 25,
  AnyEmployeeMarksCreate = 26
}
